[package]
name = "primefactors-deen13"
version = "0.1.0"
authors = ["Dennis Dierkes <dierkes@smartsquare.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
